input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["weather-data"]
    codec => json
  }
}

filter {
  mutate {
    add_field => { "debug_info" => "Pipeline Logstash Actif" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "meteo-index"
  }
  stdout { codec => rubydebug }
}
